IGNF/geoportal-extensions

README.md
=> ajout d'un "s" à OpenLayers 3

README-leaflet.md
Problème sur l’interprétation du markdown par GitHub...
=> README-leaflet.md

res/common/GPlayerSwitcher.css, res/common/GPsearchEngine.css, res/leaflet/Controls/LayerSwitcher/GPlayerSwitcherLeaflet.css, res/ol3/Controls/LayerSwitcher/GPlayerSwitcherOL3.css, samples/leaflet/LayerSwitcher/amd-default.html, samples/ol3/LayerSwitcher/amd-2-component.html, src/Common/Controls/DrawingDOM.js, src/Common/Controls/ElevationPathDOM.js, src/Common/Controls/IsoDOM.js, src/Common/Controls/LayerImportDOM.js, src/Common/Controls/LayerSwitcherDOM.js, src/Common/Controls/LocationSelectorDOM.js, src/Common/Controls/MeasureAreaDOM.js, src/Common/Controls/MeasureAzimuthDOM.js, src/Common/Controls/MeasureLengthDOM.js, src/Common/Controls/ReverseGeocodingDOM.js, src/Common/Controls/RouteDOM.js, src/Common/Controls/SearchEngineDOM.js, src/Common/Utils/SelectorID.js, src/Leaflet/Controls/LayerSwitcher.js, src/Leaflet/Controls/LocationSelector.js, src/Leaflet/Controls/MousePosition.js, src/Leaflet/Layers/LayerEvent.js, src/Leaflet/Layers/WMS.js, src/Leaflet/Layers/WMTS.js, src/Ol3/Controls/LayerSwitcher.js, src/Ol3/Controls/MousePosition.js
Mise en place du mécanisme d'identifiant unique sur l'extension LayerSwitcher sous Leaflet et ol3.
=> Feature LayerSwitcher 

samples/ol3/MousePosition/bundle-edit-coordinates.html, src/Common/Controls/MousePositionDOM.js, src/Vg/Controls/MousePosition.js
Quelques modifications suite à la PR #117, notamment sur la gestion des conséquences sur l'extension VG.
=> fix editCoordinates default value to false on vg control

src/Common/Controls/MousePositionDOM.js
=> really fix default values for editCoordinates in any cases

samples/leaflet/MousePosition/bundle-custom-editCoordinates.html, src/Leaflet/Controls/MousePosition.js, src/Ol3/Controls/MousePosition.js
Fix #138 : bug when locating geographical coordinates with Leaflet extension
Fix #140 : solve conflict when displayCoordinates:false and editCoordinates:true
=> MousePosition coordinates edition : bug fixes

src/Itowns/GlobeViewExtended.js
fixes GlobeViewExtended so LayerSwitcher and Attributions controls work fine.
=> fix (controls) : fixes GlobeViewExtended 

README-leaflet.md, README-ol3.md, README.md
On en profite pour faire disparaître le 3 de OL3 dans la doc
=> Add npm installation instructions to READMEs

CONTRIBUTING.md, CONTRIBUTORS.md
=> Adds contributions files

COMPILE.md, gulpfile.js, samples-src/pages/leaflet/Default/pages-leaflet-es6.html, samples-src/pages/ol3/Default/pages-ol-es6.html, samples-src/templates/leaflet/layout-leaflet-sample-es6.hbs, samples-src/templates/ol3/ol-sample-es6-layout.hbs, samples-src/templates/partials/leaflet/partials-leaflet-es6-head.hbs, samples-src/templates/partials/ol3/partials-ol-es6-head.hbs, src/Config.js, utils/template/README, utils/template/UMD.tpl
maj de l'entête UMD sur les bundles 
* Maj du template UMD pour une compatibilité avec cjs, amd, es6 module...
* Exemples d'import du bundle dans un module ES6
=> maj de l'entête UMD sur les bundles

src/OpenLayers/GfiUtils.js
[issue #203](https://github.com/IGNF/geoportal-extensions/issues/203)
=> contrôle gfi openlayers : prise en compte des couches vecteur tuilées

res/Common/GPmousePosition.css, samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-amchart.html, samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-d3.html, samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-raw.html, samples-src/pages/leaflet/MousePosition/pages-leaflet-mouseposition-amd-opts-editcoordinates.html, samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-option-markerdisplay.html, samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options-services.html, samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options.html, samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-options.html, samples-src/pages/openlayers/MousePosition/pages-ol-mouseposition-bundle-default.html, samples-src/pages/openlayers/MousePosition/pages-ol-mouseposition-bundle-opts-editcoordinates.html, src/Common/Controls/MousePositionDOM.js, src/Leaflet/Controls/Controls.js, src/Leaflet/Controls/MousePosition.js, src/OpenLayers/Controls/MousePosition.js, webpack.config.itowns.js, webpack.config.leaflet.js, webpack.config.mix.js, webpack.config.openlayers.js
cf. issue #149, issue #202 et issue #159  sur l'extension MousePosition
=> Extension MousePosition : ajout jsdoc sur l'option editCoordinates + bug d'affichage

src/Common/Utils/Register.js, src/Itowns/GpPluginItowns.js, src/Leaflet/CRS/CRS.js, src/OpenLayers/CRS/CRS.js, test/spec/Common/Utils/test-common-utils-register.js
- Export the CRS class into the iTowns object
- Refactor Register() to take proj4 as parameter (Leaflet and Openlayers)
=> Export CRS in iTowns

src/Itowns/GlobeViewExtended.js, test/spec/itowns/test_itowns-GlobeViewExtended.js, test/spec/openlayers/Controls/test_ol-controls-editor.js, test/spec/openlayers/Controls/test_ol-controls-mouseposition.js
- correction des tests unitaires ol et it
- setAzimuth et setTilt de GlobeViewExtent renvoient des Promises
Reste 1 test qui ne passe pas pour l'extension itowns. En attente de la réponse de l'équipe Itowns pour savoir si ce comportement est normal.
=> fix(ol/it:Test) : corrections pour passage des tests unitaires

doc/README-itowns.md, samples-src/pages/itowns/MiniGlobe/pages-itowns-miniglobe-amd.html, samples-src/pages/itowns/MiniGlobe/pages-itowns-miniglobe-bundle.html, samples-src/pages/itowns/Scale/pages-itowns-scale-amd.html, samples-src/pages/itowns/Scale/pages-itowns-scale-bundle.html, src/Itowns/Controls/Attributions.js, src/Itowns/Controls/LayerSwitcher.js, src/Itowns/Controls/MiniGlobe.js, src/Itowns/Controls/MousePosition.js, src/Itowns/Controls/Scale.js, src/Itowns/Controls/Widget.js, src/Itowns/GlobeViewExtended.js
- L'option "position" du widget MiniGlobe est forcée à l'initialisation à "absolute"
- L'option "element" ne prenne uniquement une string en entré (id de la div)
- Possibilité de mettre en entré de l'option element un element html OU l'id d'un element html
- Si l'option 'target' n'est pas renseignée (c'est alors la viewerDiv qui est prise par défaut), l'option 'position' a pour valeur par défaut "absolute"
- Si l'option 'target' est renseignée, l'option 'position' a pour valeur par défaut "relative"
- L'option 'position' du widget MiniGlobe n'est plus forcée à "absolute"
=> fix(it:Controls) : debug de l'initialisation de la position des widgets

src/Common/Controls/ProfileElevationPathDOM.js, src/Itowns/Controls/MousePosition.js, src/Itowns/GlobeViewExtended.js, src/OpenLayers/Controls/ElevationPath.js, src/OpenLayers/Controls/LocationSelector.js, src/OpenLayers/Controls/MousePosition.js, src/OpenLayers/Controls/SearchEngine.js
Changer la visibilité d'une couche vecteur tuilé n'a aucun effect sur ses labels associés, en 3D (itowns)
Numéro du ticket : 
RDEV-36067
Les labels disparaissent et reaparaissent en fonction de la visibilité de la couche vecteur tuilé associée, en 3D (itowns)
=> fix(layers:VT): synchro visibilité layer/labels

src/Common/Controls/ProfileElevationPathDOM.js
La précédente PR sur le profil alti a cassé les profils avec amCharts, et abîmé ceux avec D3. Avec cette branche, résolution des problèmes introduits (seul code modifié : dans les fonstions spécifiques à amCharts et D3)
Bug intrdoduit :
=> Fix profil alti amcharts

src/Leaflet/Controls/ElevationPath.js
- profil alti sur leaflet était cassé
- maintenant il est pas cassé
-
=> Fix profil altimétrique Leaflet

src/OpenLayers/Controls/ElevationPath.js
Saisie à main levée du profil alti par défaut ne fonctionne pas bien, surtout si faite lentement
- Résvision de la gestion du sampling 
- Correction du bug
=> fix ol:ElevationPath saisie à main levée foireuse

DRAFT_CHANGELOG.md, src/OpenLayers/Controls/Utils/Interactions.js
=> Fix sur les interactions de l'outil de dessin

build/jsdoc/README-itowns.md, build/jsdoc/README-leaflet.md, build/jsdoc/README-openlayers.md, src/Leaflet/Layers/Layers.js
Retrait des mentions à professionnels.ign.fr dans la doc
Retrait des map.json non fonctionnels
=> docs(common:Doc): Retrait mentions professionnels.ign.fr

samples-src/pages/leaflet/ReverseGeocode/pages-leaflet-reversegeocode-bundle-default.html, src/Leaflet/Controls/Controls.js, src/Leaflet/Controls/ElevationPath.js, src/Leaflet/Controls/ReverseGeocoding.js, src/Leaflet/Controls/SearchEngine.js, src/Leaflet/Controls/Utils/IconDefault.js, src/Leaflet/Layers/WMS.js, src/Leaflet/Layers/WMTS.js
=> Ajout event 'reverse:onclickresult' sur le controle ReverseGeocoding

DRAFT_CHANGELOG.md, samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-default.html, src/Leaflet/Controls/Controls.js, src/Leaflet/Controls/SearchEngine.js
=> Ajout events sur le controle SearchEngine Leaflet

src/Leaflet/CRS/EPSG2154.js
Le chargement des résolutions de l'EPSG:2157 (L93) échouait et renvoyait une erreur.
Changement du nom du CRS L93 en LAMB93-5cm
fix #378
=> fix(ll:CRS): corrige nom du CRS -> LAMB93_5cm

src/OpenLayers/Controls/ElevationPath.js
https://github.com/IGNF/geopf-extensions-openlayers/pull/303
=> fix profil alti trop gros

src/OpenLayers/Controls/ElevationPath.js
cf cf https://github.com/IGNF/geopf-extensions-openlayers/pull/385
=> fix(profil-alti): les pentes sont mal calculées
