IGNF/geoportal-extensions

src/Ol3/Controls/LayerImport.js

Try to find crs.toUpperCase() (not only crs) in openlayers projections definitions, in order to know if WMS or WMTS GetCapabilities layer can be added to map.
(for instance if crs = "epsg:3857")

fix #59 : try ol.proj.get(crs.toUpperCase()) (e.g. if crs="epsg:3857")

---

README-leaflet.md
README-ol3.md

Le premier site est dépassé et n'est plus maintenu. Il n'est plus recommandé ni même cité dans le workshop officiel OpenLayers http://openlayers.org/workshop/layers/cached.html ou les exemples.

Remplacement de la référence vers spatialreference.org par epsg.io

---

src/Ol3/Controls/LayerImport.js

- fix #52 
- removes whitespaces from both ends of url

Feature ol3 layerimport : get correct geographical extent for WMS layers (#52)

---

samples/ol3/Drawing/index-amd.html
src/Common/Controls/DrawingDOM.js
src/Ol3/Controls/Drawing.js
src/Ol3/Controls/ElevationPath.js
src/Ol3/Controls/Measures/MeasureAzimuth.js
src/Ol3/Controls/Measures/MeasureLength.js
src/Ol3/Controls/Measures/Measures.js
src/Ol3/Controls/Utils/Interactions.js

Mise en place d'un mécanisme (simple) pour gérer les interactions entre extensions.
_Pourquoi et comment l'utiliser ?_
Cette classe permet de gérer les interactions entre chaque extension.
Une extension qui met en place une interaction avec la carte, doit désactiver
les autres interactions en cours sur les autres extensions.
La désactivation d'une interaction s'accompagne d'actions telles que
le nettoyage des dessins, la réinitialisation de l'état graphique, ...
_Exemples :_
Pour désactiver toutes les interactions, et exécuter l'opération par défaut : clean
`Interactions.unset(map);`
Pour désactiver les interactions sauf celles de **Drawing**. 
Et on souhaite exécuter des opérations particulières : status, collapse et message
```
Interactions.unset(map, {
current : "Drawing",
status : …
```

Gestion des interactions entre extensions

---

src/Ol3/GfiUtils.js

Au clic sur les features KML ou GPX, certains attributs non pertinents sont présentés : 
* styleUrl : instructions de style des KML
* extensionsNode_ : dans le GPX
Ces attributs étaient filtrés lorsque le getfeatureInfo était géré au niveau du SDK, mais cela a du se perdre dans le rajout du controle GetFeatureInfo.

Reintroduce filtering of unwanted properties in popups

---

src/Common/Controls/MousePositionDOM.js

Au survol des coordonnées, lorsque le mode édition n'est pas activé, le label "Cliquer pour saisir des coordonnées" ne devrait pas s'afficher.
Voir :  #134

fix #134 : mouseposition coordinates edition : display label only when editCoordinates is true

---

src/Leaflet/Controls/MousePosition.js
src/Ol3/Controls/MousePosition.js
src/Vg/Controls/MousePosition.js

L'affichage des unités des coordonnées dans l'outil d'affichage de la position de la souris (MousePosition) n'était effectif que pour les degrés sexagécimaux et pour les coordonnées métriques (m et km). (voir #135)
Cette PR permet de les afficher aussi dans le cas des degrés décimaux, des radians et des grades, pour les différentes librairies sous-jacentes.

fix #135 : display mouseposition coordinates units

---

samples/ol3/Originators/index-default-controls.html
src/Ol3/Controls/GeoportalAttribution.js

to preserve other attributions, OSM for instance

fix #146 : clean previous attributions only for Geoportal Layers

---

res/Common/GPdrawing.css
res/Ol3/Controls/ToolBoxMeasure/GPtoolBoxMeasureOL3.css

> En installant le SDK, je me suis aperçu de plusieurs coquilles dans les fichiers CSS. Par deux fois on peut lire le sélecteur suivant :
> div[^=GPdrawingPanel-]
> div[^=GPdrawingBasicPanel-]
>  
> Le souci est que rien n’est défini comme attribut matchant la chaîne de caractères. Je pense qu’il manque un id :
> div[id^=GPdrawingPanel-]
> div[id^=GPdrawingBasicPanel-]
>  
> Autre coquille relevée : il y a des caractères bizarres avant et après la propriété margin-top:auto du sélecteur ul#data-default
> On trouve le même caractère bizarre après la propriété display:inline-block du sélecteur #GPtoolbox-measure-main
>  
> Dans le meilleur des cas, les règles CSS ne seront pas appliquées. Dans le pire (c’est ce qui m’est arrivé), si le déploiement Web passe par une étape de précompilation …

Debug CSS rules based on dje remarks

---

src/Ol3/Controls/GetFeatureInfo.js
src/Ol3/GfiUtils.js

Voir issue #170 
Cet ajout permet à l'utilisateur de renseigner les options autoPan, autoPanAnimation et autoPanMargin dans l'objet GetFeatureInfo, afin de personnaliser l'affichage de la pop-up lorsqu'elle apparaît en dehors du canvas.

Ajout du paramètre autoPanOptions pour permettre le recentrage automatique des pop-up

---

src/Ol3/GfiUtils.js

Voir issue #170 
Recentrer la pop-up lorsqu'elle apparait en dehors du canvas est un comportement classique !

Recentrage de la pop-up lorsqu'elle apparaît en dehors du canvas

---

src/Common/Controls/SearchEngineDOM.js
src/Ol3/Controls/SearchEngine.js

Personnalisation du placeholder (défaut : "Rechercher un lieu, une adresse")
Possibilité de ne pas afficher de marker lorsqu'un résultat est trouvé
Possibilité de personnaliser l'affichage du marker selon les styles pré-établis

Customisation du SearchEngine

---

samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options-services.html
src/Common/Controls/SearchEngineDOM.js
src/Leaflet/Controls/SearchEngine.js

Mise en place de la navigation avec les touches du clavier sur les résultats de l'autocompletion...
+ bug sur la recherche par geocodage de l'extension Leaflet en passant le bon paramètre `returnFreeform=true` à la requête...
Cette PR fait suite à l'issue #164 ...

Extension SearchEngine : navigation avec les touches du clavier sur les résultats de l'autocompletion

---

README-itowns.md
README-leaflet.md
README-openlayers.md

Dans les readme des différentes extensions Géoportail (OpenLayers, Leaflet, iTowns), ajout d'un paragraphe indiquant comment accéder aux dernières versions stables des binaires en ligne, sur ignf.github.io.
Par ex : http://ignf.github.io/geoportal-extensions/openlayers-latest/dist/GpPluginOpenLayers-src.js

Ajout de documentation (dans les readme) : scripts en ligne et widgets Scale et Miniglobe pour itowns

---

res/OpenLayers/Controls/LayerImport/GPimportOpenLayers.css
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-wms-cors-proxy.html
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-wms-proxy.html
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-wmts-proxy.html
samples-src/resources/proxy/proxy.php
src/Common/Controls/LayerImportDOM.js
src/OpenLayers/Controls/LayerImport.js

cf. issue #61 
L'import des couches WMS (ou WMTS), les couches est organisées en catégorie (ou arborescence). Il est possible de plier/déplier les catégories.
**TODO**
> - gestion des messages d'erreurs (à réaliser dans une autre PR)
> - customisation des puces des rubriques 
Exemples pour tester cette fonctionnalité : 
- http://localhost/samples/openlayers/LayerImport/pages-ol-layerimport-bundle-wms-proxy.html
- http://localhost/samples/openlayers/LayerImport/pages-ol-layerimport-bundle-wmts-proxy.html

Structurer l'import des couches WMS en rubrique

---

src/Itowns/Controls/MousePosition.js
src/Itowns/Layer/LayerWMS.js
src/Itowns/Layer/LayerWMTS.js
src/Leaflet/Controls/ElevationPath.js
src/Leaflet/Controls/Isocurve.js
src/Leaflet/Controls/MousePosition.js
src/Leaflet/Controls/ReverseGeocoding.js
src/Leaflet/Controls/Route.js
src/Leaflet/Controls/SearchEngine.js
src/Leaflet/Layers/Layers.js
src/OpenLayers/Controls/ElevationPath.js
src/OpenLayers/Controls/Isocurve.js
src/OpenLayers/Controls/LocationSelector.js
src/OpenLayers/Controls/MousePosition.js
src/OpenLayers/Controls/ReverseGeocode.js
src/OpenLayers/Controls/Route.js
src/OpenLayers/Controls/SearchEngine.js
src/OpenLayers/Layers/LayerWMS.js
src/OpenLayers/Layers/LayerWMTS.js
src/OpenLayers/Layers/SourceWMS.js
src/OpenLayers/Layers/SourceWMTS.js

Utilisation du https par défaut sur les controles et l'ajout de couche Géoportail.
Paramétrable avec l'option ssl : false lors de l'ajout de couche ou control pour forcer du http.
La documentation a été mise à jour en ce sens.

Utilisation du https par défaut

---

CHANGELOG.md
package.json
samples-src/pages/leaflet/Default/pages-leaflet-amd.html
samples-src/pages/leaflet/Default/pages-leaflet-bundle.html
samples-src/pages/leaflet/Default/pages-leaflet-es6.html
samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-amchart.html
samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-d3.html
samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-default.html
samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-amd-raw.html
samples-src/pages/leaflet/ElevationPath/pages-leaflet-elevationpath-bundle-default.html
samples-src/pages/leaflet/MousePosition/pages-leaflet-mouseposition-amd-default.html
samples-src/pages/leaflet/MousePosition/pages-leaflet-mouseposition-amd-opts-editcoordinates.html
samples-src/pages/leaflet/MousePosition/pages-leaflet-mouseposition-bundle-default.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-default.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-option-markerdisplay.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options-services.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options-trigger.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-amd-options.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-default.html
samples-src/pages/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-options.html
src/Leaflet/Controls/Utils/IconDefault.js

> Réaliser une recherche avec le widget *SearchEngine* Leaflet, et valider l'affichage du *marker*
À valider pour les **OS Mobile** avec l'URL suivante :
https://geoportail.000webhostapp.com/extensions/samples/leaflet/SearchEngine/pages-leaflet-searchengine-bundle-default.html

issue #234 : gestion des icônes pour des écrans Retina (Extensions Leaflet)

---

samples-src/pages/openlayers/Isocurve/pages-ol-isocurve-bundle-drive.html
src/OpenLayers/Controls/Isocurve.js
src/OpenLayers/Controls/LocationSelector.js

cf. issue #246 
nouvelle méthode publique sur le widget Isocurve qui permet de prépositionner un point sur la carte et de faire un traitement isochrone ou isodistance.
> Pour info, Leaflet implémente déjà ces méthodes publiques
**exemple**
```
var iso = new ol.control.Isocurve({});
iso.compute([288000, 6247900], "0.32", {
direction : "arrival",
method : "time",
transport : "Pieton",
exclusions : []
});
```
**jsdoc**
**resultat** _cf. samples/openlayers/Isocurve/pages-ol-isocurve-bundle-drive.html_

nouvelle méthode sur le widget Isocurve (ol)

---

src/Itowns/Layer/LayerElevation.js
src/Itowns/Layer/LayerWMS.js
src/Itowns/Layer/LayerWMTS.js

- tag gp-itowns-ext dans requêtes images envoyées via les extensions Gp pour itowns.
- numéro de version des extensions géoportail pour itowns visible dans tag
Utile pour : 
- compter les requêtes réalisée via les extensions géoportail pour itowns. 
- compter les utilisations des extensions itowns en fonction de leur version

Ajout du tag "gp-itowns-ext" dans les requêtes WMTS et WMS via iTowns

---

DRAFT_CHANGELOG.md
src/OpenLayers/CSS/Controls/SearchEngine/GPsearchEngineOpenLayers.css

Ajout d'un ascenseur (en mode auto)  sur la fenêtre de résultats de l'autocompletion du widget **SearcEngine** : 
cf. https://www.developpez.net/forums/d2125691/applications/sig-systeme-d-information-geographique/ign-api-geoportail/geoportal-extension-searchengine-autocomplete-maximum-5-reponses/#post11811536

Retrait de la limitation du nombre d'affichage des resultats de l'autocompletion

---

DRAFT_CHANGELOG.md
src/OpenLayers/Controls/Drawing.js

Correctif du style des éléments en cours d'édition lors de l'export / enregistrement des croquis sur l'outil de dessin.
Lors de la sélection d'un élément à modifier, le style en surbrillance est ajouté au _feature_ sélectionné.
Si on procède à l'export sans avoir au préalable validé la modification du _feature_, le style de surbrillance est enregistré dans l'export.
La correction consiste à invalider les _features_ en cours d'édition avant de lancer l'export ou l’enregistrement.
Comment tester ?
- créer un croquis
- sélectionner un élément (feature) pour modification
- ne pas invalider la modification (toujours en surbrillance)
- exporter le croquis
- importer ce même croquis
> le style doit être correctement appliqué !

Fix sur le style des elements en cours d'édition

---

DRAFT_CHANGELOG.md
src/OpenLayers/Controls/Measures/Measures.js

Les outils de mesures ne permettaient pas la saisie de point sous la **tooltip** de mesure.
(remontée utilisateur)

Fix sur la saisie sous les tooltips avec les outils de mesures

---

DRAFT_CHANGELOG.md
src/OpenLayers/Controls/Measures/Measures.js

A la suppression de la couche ou à la désactivation des mesures, on nettoie correctement les **tooltips** sur la carte.

Fix sur le nettoyage des tooltips des outils de mesures

---

src/OpenLayers/Controls/LayerImport.js

Import WMS "https://adour-garonne.eaufrance.fr/servicesOGCs?" ne fonctionne pas.
S'il y a plusieurs projections dans le getCap pour une couche donnée, on regarde juste si la première correspondà celle de la carte en cours. Si non, on récupére la projection en question depuis Openlayers... 
Import WMS "https://adour-garonne.eaufrance.fr/servicesOGCs?" fonctionne.
Maintenant on boucle sur toutes les projections issues du getCap, et si aucune d'entres elles ne correspond à celle de la carte, on va chercher du côté d'OpenLayers en bouclant de la même manière (première projection gérée retournée)
Si aucune ne correspond, on maitient le comportement initial en renvoyant …

fix(ol:Import): projection mieux geree pour les couches

---

src/Leaflet/Controls/Route.js

Prise en compte des options routeOptions.onSuccess et routeOptions.geometryInInstructions passées à la création du widget
Les options `routeOptions.onSuccess` et `routeOptions.geometryInInstructions` dans le code d'exemple suivant 
```js
// Geoportail widget route
const route = L.geoportalControl.Route({
apiKey: "calcul",
disableReverse: true,
graphs: ["Pieton"],
routeOptions: {
onSuccess: computeRouteElevation,
geometryInInstructions: false,
},
});
map.addControl(route);
```
ne sont pas prises en compte.
Ces deux options sont désormais prises en compte

feat(leaflet-route): more options passed to route

---

DRAFT_CHANGELOG.md
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-mapbox-event-fail-source.html
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-mapbox-event-fail-sprites.html
samples-src/pages/openlayers/LayerImport/pages-ol-layerimport-bundle-mapbox-event-fail-syntax.html
samples-src/resources/data/mapbox/styles/bati_failed_source.json
samples-src/resources/data/mapbox/styles/bati_failed_sprites.json
samples-src/resources/data/mapbox/styles/bati_failed_syntaxe.json
samples-src/resources/data/mapbox/styles/bati_sans_sprites.json
src/Common/Controls/ProfileElevationPathDOM.js
src/OpenLayers/Controls/LayerImport.js

Ajout des événements pour l'application du rendu des styles **MapBox** : 
* "render:success"
* "render:failure" 
Ajout de l’événement pour le chargement de l'editeur de style :
* "editor:loaded" 
Exemple de _listeners_ :
```js
map.on("editor:loaded", function (e) {
// l'éditeur de style est chargé dans le DOM
console.info(e);
})
map.on("render:failure", function (e) {
// le rendu du style sur la couche est en échec
console.error(e);
})
map.on("render:success", function (e) {
// le rendu du style sur la couche est bien appliqué
console.info(e);
})
```

Ajout des evenements sur le rendu des styles mapbox

---

DRAFT_CHANGELOG.md
src/OpenLayers/Controls/Drawing.js
src/OpenLayers/Controls/ElevationPath.js
src/OpenLayers/Controls/GeoportalAttribution.js
src/OpenLayers/Controls/GetFeatureInfo.js
src/OpenLayers/Controls/Isocurve.js
src/OpenLayers/Controls/LayerImport.js
src/OpenLayers/Controls/LayerSwitcher.js
src/OpenLayers/Controls/LocationSelector.js
src/OpenLayers/Controls/MousePosition.js
src/OpenLayers/Controls/ReverseGeocode.js
src/OpenLayers/Controls/Route.js
src/OpenLayers/Controls/SearchEngine.js
src/OpenLayers/Formats/GPX.js
src/OpenLayers/Formats/GeoJSON.js
src/OpenLayers/Formats/KML.js
src/OpenLayers/Layers/LayerWMS.js
src/OpenLayers/Layers/LayerWMTS.js

Liste exhaustive des modules : 
Ceci permet de connaitre le chemin des modules pour un appel ES6 module :
> Pour info, cette demande est liée à l'issue #345 : _comment connaitre la liste des modules importables_

Ajout des modules dans la JSdoc

---

DRAFT_CHANGELOG.md
samples-src/pages/openlayers/ReverseGeocode/pages-ol-reversegeocode-bundle-cb.html
src/OpenLayers/Controls/ReverseGeocode.js

Ajout de l’événement _'reversegeocode:onclickresult'_ sur le contrôle **ReverseGeocode** pour OpenLayers
cf. #355

Ajout event sur le controle ReverseGeocode (ol)

---

src/OpenLayers/Controls/ElevationPath.js

fix(elevation): correction du profil altimétrique en cas de boucle
